
const settings = {
    STATE_UPDATE_INTERVAL: parseInt(process.env.REACT_APP_STATE_UPDATE_INTERVAL),
    PUBLIC_RPC_URL: process.env.REACT_APP_PUBLIC_RPC_URL,
    DEBUG: process.env.REACT_APP_DEBUG,
    CHAIN_ID: process.env.REACT_APP_CHAIN_ID,
    BUY_DAI_LINK: process.env.REACT_APP_BUY_DAI_LINK,
    MEDIUM_LINK: process.env.REACT_APP_MEDIUM_LINK,
    BUY_ETH_LINK: process.env.REACT_APP_BUY_ETH_LINK,
    DOWNLOAD_WALLET: process.env.REACT_APP_DOWNLOAD_WALLET,

    PRODUCTS: {
        INDEX_ADDRESS: '0xDBCFC1Ec8aF08aB1943aD6dEf907BD0f0b7C4fE0',
        ETH_INDEX_ADDRESS: '0x7212569605978ce4cC26489611df873706fbc2A1',
    },
};

export default settings;
